[package]
name = "para"
version = "0.1.0"
authors = ["Maor Kleinberger <kmaork@gmail.com>"]
edition = "2018"

[dependencies]
rayon = "1.5.0"
crossbeam-channel = "0.5.0"
rich-phantoms = "0.1.0"
crossbeam="0.8.0"